/*
Generated by BRIK64 L6+ route-2 bounded emitter
engine=l6_plus
claim_authority=non_claim
public_claim_allowed=false
source_pcd_sha256=sha256:0c4969cbca34ba3d21b8a533f27ce6a98c17dd59abc1ed7e9e501f6e21434d54
*/
function rust_f64_polymer_codegen(has_f64_clamp, has_polymer_context, cargo_test_passed) {
  if (has_f64_clamp === 0) return 0;
  if (has_polymer_context === 0) return 0;
  if (cargo_test_passed === 0) return 0;
  return 1;
}
module.exports = { rust_f64_polymer_codegen };
