/*
Generated by BRIK64 L6+ route-2 bounded emitter
engine=l6_plus
claim_authority=non_claim
public_claim_allowed=false
source_pcd_sha256=sha256:8cf3bff3bf2b786dd34b93de6af974324b8e7983f75855b701c3b04e1f80067f
*/
function l6_cli_materialization_contract(pcd_inputs_hash_bound, l6plus_materializer_accepts_contract, generated_artifact_hash_bound, package_hash_bound, release_manifest_hash_bound) {
  if (pcd_inputs_hash_bound === 0) return 0;
  if (l6plus_materializer_accepts_contract === 0) return 0;
  if (generated_artifact_hash_bound === 0) return 0;
  if (package_hash_bound === 0) return 0;
  if (release_manifest_hash_bound === 0) return 0;
  return 1;
}
module.exports = { l6_cli_materialization_contract };
