/*
Generated by BRIK64 L6+ route-2 bounded emitter
engine=l6_plus
claim_authority=non_claim
public_claim_allowed=false
source_pcd_sha256=sha256:ff48eaeb3848e39c5400fcbb9fc293e5fffb649db2e32454f900080be660ef1c
*/
function brik_cli_core(command_code, json_mode, ci_mode) {
  if (json_mode === 1) return 0;
  if (ci_mode === 1) return 0;
  if (command_code === 0) return 1;
  if (command_code === 64) return 64;
  return 0;
}
module.exports = { brik_cli_core };
