/*
Generated by BRIK64 L6+ route-2 bounded emitter
engine=l6_plus
claim_authority=non_claim
public_claim_allowed=false
source_pcd_sha256=sha256:041a809f8a2bdb80e0cdbe1f17445ca991c30b5b475ad666fd2a20add9199146
*/
function brik_cli_polymer(command_code, workspace_readable, certificate_present, target_code) {
  if (workspace_readable === 0) return 64;
  if (command_code === 1) return 0;
  if (command_code === 64) return 64;
  if (certificate_present === 0) return 67;
  if (target_code === 0) return 65;
  if (command_code === 2) return 1;
  return 0;
}
module.exports = { brik_cli_polymer };
